name: moi_eglise_tv
description: "La réconciliation des peuples avec Dieu - Moi Église TV mobile app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  
  # Video & Media
  video_player: ^2.8.1
  chewie: ^1.7.5
  cached_network_image: ^3.3.0
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lottie: ^2.7.0
  
  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  permission_handler: ^11.1.0
  
  # Internationalization
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter
  
  # Icons
  lucide_icons: any
  
  # Social Auth
  google_sign_in: ^6.1.6
  #sign_in_with_apple: ^5.0.0

  # Facebook Auth
  flutter_facebook_auth: ^6.1.1
  
  # HTTP
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  sqflite: ^2.3.0
  
  # Device Info
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Script
      fonts:
        - asset: assets/fonts/script-regular.ttf
    - family: SansSerif
      fonts:
        - asset: assets/fonts/sans-serif-regular.ttf
        - asset: assets/fonts/sans-serif-medium.ttf
          weight: 500
        - asset: assets/fonts/sans-serif-bold.ttf
          weight: 700